[package]
name = "validator"
version = "0.1.0"
edition = "2021"

[features]
derive=["validator_derive"]

[dependencies]
thiserror = "1.0.61"
once_cell = "1.19.0"
regex = "1.10.4"
url = "2.5.0"
lazy_static = "1.4.0"
validator_derive = { path = "../validator_derive", optional = true }