[package]
name = "validator"
version = "0.1.0"
edition = "2021"

[features]
derive=["validator_derive"]

[dependencies]
thiserror = "2.0.21"
regex = "1.13.1"
url = "2.5.8"
lazy_static = "1.5.0"
validator_derive = { path = "../validator_derive", optional = true }

[[test]]
name = "elements"
required-features = ["derive"]