[package]
name = "validator"
version = "0.1.0"
edition = "2021"

[features]
derive=["validator_derive"]

[dependencies]
thiserror = "2.0.21"
regex = "1.13.1"
url = "2.5.8"
lazy_static = "1.5.0"
validator_derive = { path = "../validator_derive", optional = true }
derive_more = { version = "2.1.1", features = ["from", "into", "deref"] }

[[test]]
name = "elements"
required-features = ["derive"]

[[test]]
name = "struct_validator"
required-features = ["derive"]

[[test]]
name = "password_validator"
required-features = ["derive"]
